const birddata = [
    {
        name: `Avocet`,
        summary: `The bird from the RSPB logo! In Marshside, they seem lonely. When I was at Parkgate, there was tonnes of them but even further away, I should really look into getting an extender. Cool looking distinct bird.`,
        imageCount: 3,
        date: `27/04/2026`,
        location: `Marshside`,
        whatStatus: ``,
    }, {
        name: `Black Swan`,
        summary: `Visited a friend in London hoping to see some birds and despite the awful rain, I saw this celebrity. Had about 4 eggs, one slightly cracked. It kept bothering a Mute Swan to further build up the nest. Glad the trip was not wasted! Native to Australia but some escapees have successfully bred in UK, especially in Devon.`,
        imageCount: 4,
        date: `06/06/2026`,
        location: `Hyde Park`,
        whatStatus: ``,
    }, {
        name: `Blackbird`,
        summary: `Female is brown so I hate the name! Often seen in Winter on the ground flicking leaves around but in Spring, it loves to sing early in the morning and is the first heard during the 'Dawn chorus' Prominent yellow ring around the eye helps distinguish it from other small brown birds.`,
        imageCount: 3,
        date: `11/05/2026`,
        location: `Thurstaston`,
        whatStatus: ``,
    }, {
        name: `Barn Swallow`,
        summary: `Or Swallow as it's just called in the UK. Prongs on the tail helps it stand out from other swallows. Arrives in April then leaves around October. Fast flyers but thankfully unlike Sand Martins they do like to rest now and then which makes for easier photographing.`,
        imageCount: 3,
        date: `18/04/2026`,
        location: `Holyhead`,
        whatStatus: ``,
    }, {
        name: `Black-headed Gull`,
        summary: `A cute small gull but I hate the name. The black-head it's named for is only there during breeding season, otherwise it's more of an ink smudge. And I would argue it's more brown than black. Add it to the list of bad bird names!`,
        imageCount: 6,
        date: `24/06/2026`,
        location: `Birkenhead Park`,
        whatStatus: ``,
    }, {
        name: `Black-tailed Godwit`,
        summary: `Large wader that in Summer have brighter orange chests. Sadly my photo was taken in Winter which is when they are the most common in the UK and also means it looks a bit drab. That said, was happy to get a photo of it at Southport`,
        imageCount: 1,
        date: `22/02/2026`,
        location: `Marshside`,
        whatStatus: ``,
    }, {
        name: `Brent Goose`,
        summary: `An uncommon goose only here during the Winter and along our coasts. Arrives in October and leaves in April so just about got to these in time. eBird really helped me figure out how to find them and easy access to Hilbre Island made it possible. The white patch on the neck helps it stand out from other geese.`,
        imageCount: 2,
        date: `06/04/2026`,
        location: `Hilbre Island`,
        whatStatus: ``,
    }, {
        name: `Buzzard`,
        summary: `Huge bird I mostly see in the air far away. In 2025, I was very lucky to get a photo of one that landed nearby and spoke to an old man about it who asked me if I worked for Naturewatch and said it was a Peregrine Falcon. Wrexham was quite disappointing bird wise as I got lost easily so glad I got this photo.`,
        imageCount: 3,
        date: `10/05/2026`,
        location: `Wrexham`,
        whatStatus: ``,
    }, {
        name: `Canada Goose`,
        summary: `Honk! Accidentally disturbed a nest on a very tiny almost inaccessible island when I was in Wigan but I quickly left em alone. Since then I have seen goslings everywhere and maybe now, I have come to like these birds, sorta. I love how happy the goslings appear and yet the parents look aggressive and miserable.`,
        imageCount: 5,
        date: `11/04/2026`,
        location: `Horrock's Flash`,
        whatStatus: ``,
    }, {
        name: `Chaffinch`,
        summary: `A bird with a lovely song/call. A small amount of repetitive notes followed by a fancy flourish. The males have a lovely colour palette. Often difficult to see through the sticks of trees they perch high upon but at least the colours of the male makes it easier to spot.`,
        imageCount: 5,
        date: `02/05/2026`,
        location: `Tipton`,
        whatStatus: ``,
    }, {
        name: `Chicken`,
        summary: `Should I even count this? I will cos that Silverdale walk was lovely and there was a lot of them.`,
        imageCount: 1,
        date: `07/03/2026`,
        location: `Silverdale`,
        whatStatus: ``,
    }, {
        name: `Chiffchaff`,
        summary: `Got the name from the call it's makes which sounds a lot like "chiff, chaff" over and over. Likes to be very high atop trees which made them difficult to spot the first time I was hearing them. They are small and brown too which didn't help. Once you know the call, it's easy to know when you are near one.`,
        imageCount: 2,
        date: `06/04/2026`,
        location: `Thurstaston`,
        whatStatus: ``,
    }, {
        name: `Coal Tit`,
        summary: `A surprisingly hard bird to find. I love their muted colours. Often I photograph a great tit hoping it's a coal tit, but sadly not. I was in Princes Park once and saw one flying about with some lovely trees with pink leaves in the background but there was too many kids around so I didn't get my camera out. Maybe next time!`,
        imageCount: 1,
        date: `10/05/2026`,
        location: `Wrexham`,
        whatStatus: ``,
    }, {
        name: `Collared Dove`,
        summary: `One of many doves I have found and barely seen since. Glad I got this photo when I did. Originally from Asia. They are named after their strip along the neck resembling a collar.`,
        imageCount: 1,
        date: `10/01/2026`,
        location: `Liverpool to Leeds Canal`,
        whatStatus: ``,
    },
    {
        name: `Common Tern`,
        summary: `I went to Oakham to see Osprey but went to the wrong birding centre and didn't have time to correct that. So I am thankful I saw these not so little terns on a small island next to the similar Black-headed Gulls. They will likely be seen anywhere in the world due to having cirumpolar distribution and love to spend their entire lives in Summer regions.`,
        imageCount: 3,
        date: `03/07/2026`,
        location: `Rutland Water Nature Reserve`,
        whatStatus: ``,
    }, {
        name: `Common Whitethroat`,
        summary: `Originally I didn't know there was two types of Whitethroat but then this one looked different to my other and I learned thanks to the RSPB book that there was both Common and Lesser. Summer visitor so here between April and October. Very noisy and is named after the white throat it has.`,
        imageCount: 3,
        date: `23/05/2026`,
        location: `Thurstaston`,
        whatStatus: ``,
    }, {
        name: `Coot`,
        summary: `A common sight in all parks that many probably don't know the name of; and a moorhen is usually close by too. The chicks are quite nasty looking. They are bad parents and often kill the one that cries the most.`,
        imageCount: 3,
        date: `02/05/2026`,
        location: `Tipton`,
        whatStatus: ``,
    }, {
        name: `Crow`,
        summary: `Often I see a large crow and think it's a raven but it never is. Smart birds apparently, as they will often take advantage of human behaviour to do things such as breaking the shells of nuts by putting them on roads.`,
        imageCount: 2,
        date: `02/05/2026`,
        location: `Tipton`,
        whatStatus: ``,
    }, {
        name: `Curlew`,
        summary: `April 21st is World Curlew Day! A funny looking bird with a huge beak often seen on farms or coasts. Declining population though which is sad to hear.`,
        imageCount: 2,
        date: `22/02/2026`,
        location: `Marshside`,
        whatStatus: ``,
    }, {
        name: `Dunlin`,
        summary: `A small and social wader found along the coast. I think they're really cute as their black belly in breeding season looks like they sat down in dirt for too long. The Mersey Estuary has up to 50,000 dunlins.`,
        imageCount: 2,
        date: `17/05/2026`,
        location: `Hilbre Island`,
        whatStatus: ``,
    }, {
        name: `Dunnock`,
        summary: `A small bird with a grey ring around the neck. Quiet, shy and spends most of the time on muddy paths similar to Blackbirds. The first time I saw one, it kept flying away from me and hiding in bushes back in the Winter. Often looks grumpy.`,
        imageCount: 4,
        date: `25/06/2026`,
        location: `Thurstaston`,
        whatStatus: ``,
    }, {
        name: `Egyptian Goose`,
        summary: `Saw it alone in Sheffield which was quite sad to see but made it quite special; then I go to London and there's 100s of them! Fancy looking goose compared to others. `,
        imageCount: 2,
        date: `28/02/2026`,
        location: `Rother Valley Country Park`,
        whatStatus: ``,
    }, {
        name: `Eider`,
        summary: `A fancy looking duck, well the males anyway. They sound a lot like Marge Simpson going 'oooo' as if they live in constant surprise. The male puffs up their chest like a balloon in attempt to court the lady ducks.`,
        imageCount: 1,
        date: `26/04/2026`,
        location: `Hilbre Island`,
        whatStatus: ``,
    },
    {
        name: `Gannet`,
        summary: `The bird featured on my RSPB card! Thousands were present at the Bempton Cliffs. They are huge and will often fly up from below close to your head at viewing points. Their babies look like big cuddly toys.`,
        imageCount: 9,
        date: `08/07/2026`,
        location: `Bempton Cliffs`,
        whatStatus: `new`,
    }, {
        name: `Goldcrest`,
        summary: `UK's smallest bird that weighs the same as a 5p coin. I saw them aplenty when I first got my camera and now I never see them, gutted.`,
        imageCount: 1,
        date: `30/12/2025`,
        location: `Thurstaston`,
        whatStatus: ``,
    }, {
        name: `Gadwall`,
        summary: `A dull grey looking duck. I have nothing to note of it, I barely recognise them when next to other female ducks of similar colours.`,
        imageCount: 1,
        date: `17/01/2026`,
        location: `Lunt Meadows`,
        whatStatus: ``,
    }, {
        name: `Goldfinch`,
        summary: `A very sociable bird with a warbly chirpy call. Lovely colours when lit up by the sun. The first photo I took of it was during the greyest UK weather I have ever witnessed.`,
        imageCount: 3,
        date: `11/05/2026`,
        location: `Thurstaston`,
        whatStatus: ``,
    }, {
        name: `Goosander`,
        summary: `A sick looking duck because it almost looks like it has a pompadour. Only ever seen it once during the Winter but hoping to keep an eye out for it again towards the end of the year. Only seen it far away deep into a lake.`,
        imageCount: 1,
        date: `17/01/2026`,
        location: `Lunt Meadows`,
        whatStatus: ``,
    }, {
        name: `Grey Partridge`,
        summary: `A bird that scares easily, so easily I don't see it first, which it jumping and yelling scares me more than I scared it. That said, happy to at least get 3 in one shot even if it is awful.`,
        imageCount: 1,
        date: `17/01/2026`,
        location: `Thurstaston`,
        whatStatus: ``,
    }, {
        name: `Great Black-backed Gull`,
        summary: `Often I can't tell the difference between the two, but I saw two big seagulls sat down next to eachother with very black backs and eyes that looked small. It had to be a Great Black-backed Gull! Surely? Hmm, now I am doubting it.`,
        imageCount: 1,
        date: `22/02/2026`,
        location: `Marshside`,
        whatStatus: ``,
    }, {
        name: `Cormorant`,
        summary: `One of my favourite birds! I feel sorry for it as it often just flaps its wings to dry them off due to them not having as much oil to stop the water clogging the feathers. And in parts of Asia, they are used to catch fish with a rope around their neck, becoming unable to swallow the fish and spit it back up on the boat. Poor birds!`,
        imageCount: 3,
        date: `02/05/2026`,
        location: `Tipton`,
        whatStatus: ``,
    }, {
        name: `Great Crested Grebe`,
        summary: `Ah, the Bloodborne bird (cos of the hair reminding me of the Hunter's Hat). I love how they look. Once saw one pull a worm out of it's cloaca in Tipton and it never occurred to me that birds could get worms.`,
        imageCount: 2,
        date: `02/05/2026`,
        location: `Tipton`,
        whatStatus: ``,
    }, {
        name: `Great Spotted Woodpecker`,
        summary: `Often heard but rarely seen! First photo I took of it, it was obscured by leaves but I remember seeing the lovely flash of red before me as it flew past. Also got a photo of it feeding chicks in a nest which I waited 20 minutes to get. People must've thought I was a madman.`,
        imageCount: 3,
        date: `24/05/2026`,
        location: `Royden Park`,
        whatStatus: ``,
    }, {
        name: `Great Tit`,
        summary: `A Great Small Thing is what the name translates as. The males have a 'tie' going down their chest whereas the females have a very thin line. The thicker the tie, the more attractive to females, apparently...`,
        imageCount: 2,
        date: `10/01/2026`,
        location: `Rimrose Valley Country Park`,
        whatStatus: ``,
    }, {
        name: `Greater Scaup`,
        summary: `One of the rarest birds I have seen, and yet it looks so plain, poor thing. Male remained at Marine Lake in West Kirby for a long time.`,
        imageCount: 1,
        date: `23/05/2026`,
        location: `West Kirby`,
        whatStatus: ``,
    }, {
        name: `Greenfinch`,
        summary: `Very bright green during the Summer and quite sociable with a more nasty call compared to the Goldfinch. Sadly due to the rise in trichomonosis and how easily it spreads, their numbers are declining. Clean your bird feeders and try not to use trays.`,
        imageCount: 2,
        date: `14/02/2026`,
        location: `Thurstaston`,
        whatStatus: ``,
    }, {
        name: `Grey Heron`,
        summary: `I first saw one back in 2025 above me along the Liverpool to Leeds Canal and I thought it was gonna drop down and kill me, flashbacks to Elden Ring probably. Since then, they've become one of my favourite birds to spot. I saw a couple in Tipton that were very loud as they were gathering for a nest.`,
        imageCount: 7,
        date: `10/01/2026`,
        location: `Liverpool to Leeds Canal`,
        whatStatus: ``,
    }, {
        name: `Greylag Goose`,
        summary: `Common goose with a weird mouth and loves to hiss. Often I think they're Pink Footed Geese and get them mixed up easily during the Winter. Their teeth scare me but I now often see families of them chomping on wheat in fields.`,
        imageCount: 3,
        date: `22/02/2026`,
        location: `Marshside`,
        whatStatus: ``,
    }, {
        name: `Guillemot`,
        summary: `A bird I first heard as I needed to pee near the breakwater at Holyhead. I heard a yelp from the water, looked around, didn't see nothing for a while but then it showed! I thought it was drowning, haha. They become flightless after breeding due to moulting for roughly 1-2 months. `,
        imageCount: 4,
        date: `08/07/2026`,
        location: `Bempton Cliffs`,
        whatStatus: `updated`,
    }, {
        name: `Herring Gull`,
        summary: `A common gull that I often get mixed up with Great Black-backed Gull. If it's legs are pale and the back is light grey, I assume it's this. I hope! `,
        imageCount: 2,
        date: `18/04/2026`,
        location: `Holyhead`,
        whatStatus: ``,
    }, {
        name: `House Sparrow`,
        summary: `I always photograph these hoping it's a Tree Sparrow but that has never been the case despite being away from houses. Sociable but it's a shame the females are a typical LBJ.`,
        imageCount: 7,
        date: `10/05/2026`,
        location: `Wrexham`,
        whatStatus: ``,
    }, {
        name: `Jackdaw`,
        summary: `I used to think these were just baby or smaller crows, but in the Summer, their colours separate them from other corvids easily. The bright blue eyes are a giveaway too.`,
        imageCount: 2,
        date: `22/02/2026`,
        location: `Marshside`,
        whatStatus: ``,
    }, {
        name: `Kestrel`,
        summary: `Spotted the red wings from behind and thought what the hell is that. I then spent 10 minutes photographing it from below as it stretched, gave me the evil eye and all sorts. It was quite intimate! Then in Holyhead I saw one bite the head off a lizard and then swallow it. urgh`,
        imageCount: 5,
        date: `10/01/2026`,
        location: `Rimrose Valley Country Park`,
        whatStatus: ``,
    },
    {
        name: `Kittiwake`,
        summary: `A gull that is quite easy to tell apart due to the black legs and black eyes. A crybaby bird which is supposedly how it got the name. Only here on the cliff edges and for the summer.`,
        imageCount: 6,
        date: `08/07/2026`,
        location: `Bempton Cliffs`,
        whatStatus: `new`,
    }, {
        name: `Lapwing`,
        summary: `Loud crybaby birds. I was at amazed that the first time I went to Lunt Meadows, there was over 200 of them. Since then, I've never seen as many. A guy asked me what they were and I helped him out. I love their funky hairdo. They fly a bit awkwardly which is how they got their name.`,
        imageCount: 2,
        date: `12/05/2026`,
        location: `Marshside`,
        whatStatus: ``,
    }, {
        name: `Lesser Whitethroat`,
        summary: `First time seeing one of these loud small birds was after I walked past a bush and saw it to my left. I quickly got out my camera but of course it flew off. I gave up! Then as I was leaving Speke, I was about to put my camera away but then another appeared! I was able to get a decent photo before a nearby dog scared it off.`,
        imageCount: 2,
        date: `28/04/2026`,
        location: `Speke and Garston Coastal Reserve`,
        whatStatus: ``,
    }, {
        name: `Linnet`,
        summary: `Often I see a bird, dunno what it is, later when I get back and look at my photos I think "Oh, it's just another linnet". But they are quite nice birds. They look like they are covered in blood during breeding season as the front of the chest and top of their head becomes bright red.`,
        imageCount: 5,
        date: `06/04/2026`,
        location: `Hilbre Island`,
        whatStatus: ``,
    },
    {
        name: `Little Tern`,
        summary: `Their name fits them as they are indeed very little. So little, I didn't even spot them in the viewfinder. There was not as many of them as the Common Tern. Unlike the Common Tern, these guys apparently do not visit America. Good for them!`,
        imageCount: 2,
        date: `03/07/2026`,
        location: `Rutland Water Nature Reserve`,
        whatStatus: ``,
    }, {
        name: `Long-tailed Tit`,
        summary: `A bird I find very difficult to photo as they constantly keep moving. But thankfully they are sociable and talkative so at least you know where to look. They look a bit like flying teaspoons. `,
        imageCount: 3,
        date: `10/01/2026`,
        location: `Rimrose Valley Country Park`,
        whatStatus: ``,
    }, {
        name: `Magpie`,
        summary: `I don't photograph these often and I should probably change that. The iridescent feathers can look lovely in nice lighting. Has a bad rep for eating the eggs of other birds but hey, that's nature!`,
        imageCount: 3,
        date: `01/07/2026`,
        location: `Lunt Meadows`,
        whatStatus: ``,
    }, {
        name: `Mallard`,
        summary: `A duck! A typical duck! I've seen some lovely white mallards with bright yellow beaks but for some reason never kept the photos. I love seeing breeding pairs and a mother duck with a bunch of little ducklings.`,
        imageCount: 4,
        date: `02/05/2026`,
        location: `Tipton`,
        whatStatus: ``,
    }, {
        name: `Mandarin Duck`,
        summary: `Was able to find these thanks to eBird that listed them in Arrowe Country Park as being aplenty. And for once, the site was right. I went there after work and there was so many of them and I never see them elsewhere. When I went back in June, there was no males. Where did they go!?`,
        imageCount: 4,
        date: `31/03/2026`,
        location: `Arrowe Country Park`,
        whatStatus: ``,
    }, {
        name: `Meadow Pipit`,
        summary: `The most common pipit for me, at least I assume so as I can not tell the difference between any of them. A typical LBJ but if I see it on the grass, I assume it's a Meadow Pipit`,
        imageCount: 3,
        date: `17/05/2026`,
        location: `Hilbre Island`,
        whatStatus: ``,
    }, {
        name: `Moorhen`,
        summary: `Very common in parks and a good bird to learn the name of to impress people. Weird feet.`,
        imageCount: 3,
        date: `10/01/2026`,
        location: `Liverpool to Leeds Canal`,
        whatStatus: ``,
    }, {
        name: `Muscovy Duck`,
        summary: `Saw a breeding pair in Sheffield next to multiple other geese and ducks. When I told my friend about seeing them, he told me had them as pets back in America. They are lovely with short stubby legs, but they look happy.`,
        imageCount: 1,
        date: `28/02/2026`,
        location: `Rother Valley Country Park`,
        whatStatus: ``,
    }, {
        name: `Mute Swan`,
        summary: `Quite elegant but also a bit scary. They don't seem to be as aggressive as people suspect they are, though I still wouldn't pick a fight with them. The babies (cygnets) are really adorable. `,
        imageCount: 4,
        date: `06/06/2026`,
        location: `Hyde Park`,
        whatStatus: ``,
    }, {
        name: `Nuthatch`,
        summary: `I first saw one when I was leaving the same park back in December but it was cold and my camera was put away. I can't believe it took almost 7 months to get another chance. Noisy bird that sometimes sounds like a siren and I constantly hear them but never see them. They have an iconic pose but sadly I've not seen them pose like that yet.`,
        imageCount: 3,
        date: `29/06/2026`,
        location: `Royden Park`,
        whatStatus: ``,
    }, {
        name: `Oystercatcher`,
        summary: `Cool name for a bird! I really like their bright orange beaks and red eyes. Have yet to see them catch an oyster but they do love to spend the majority of time poking away in sand on our coasts.`,
        imageCount: 3,
        date: `22/02/2026`,
        location: `Marshside`,
        whatStatus: ``,
    }, {
        name: `Pheasant`,
        summary: `Shy and loud with a sudden BAGAWWWK! I think they are pretty birds though, and they are good for removing things like ticks from cattle. I love their eyes.`,
        imageCount: 1,
        date: `28/02/2026`,
        location: `Rother Valley Country Park`,
        whatStatus: ``,
    }, {
        name: `Pied Wagtail`,
        summary: `A bird that mostly tends to show itself after I put away my camera. My friend thought this was a baby magpie. Often the UKBirds subreddit will ask for bird identification, and 99% of the time, it's a Pied Wagtail. They do love to bob their tail hence the name.`,
        imageCount: 2,
        date: `06/06/2026`,
        location: `The Regent's Park`,
        whatStatus: ``,
    }, {
        name: `Pintail`,
        summary: `I adore this duck! The long tail it is named for is really elegant looking. May often see it head down in water with it's arse in the air. I like any duck where you can easily differentiate it from a mallard.`,
        imageCount: 2,
        date: `27/04/2026`,
        location: `Marshside`,
        whatStatus: ``,
    },
    {
        name: `Pink-footed Goose`,
        summary: `Can often see flocks of them migrating over Liverpool. They love to nest together in the UK during the Winter. Caught a photo of them at the end of the year thinking it was just Greylag Geese but no, turns out it was pretty cool. Now I constantly look out for them in flocks at marshes.`,
        imageCount: 1,
        date: `30/12/2025`,
        location: `Heswall Fields`,
        whatStatus: ``,
    },
    {
        name: `Puffin`,
        summary: `A cute small bird and the logo of that book publisher. Very small and keeps to the cliffs. As I walked south of Bempton, I was becoming sad as I hadn't seen one but then I left my spot to allow a guy to walk through only for him to stand still. I went over see what fixated him and then I saw the head of a Puffun behind a rock. Thanks stranger!`,
        imageCount: 4,
        date: `08/07/2026`,
        location: `Bempton Cliffs`,
        whatStatus: `new`,
    },
    {
        name: `Razorbill`,
        summary: `A cool name. Sticks to our cliffs in the Summer. Loads of them were at Bempton Cliffs. Their beaks do indeed look a bit sharp and like a razor, so quite a fitting name! `,
        imageCount: 4,
        date: `08/07/2026`,
        location: `Bempton Cliffs`,
        whatStatus: `new`,
    },
    {
        name: `Red Breasted Merganser`,
        summary: `Only ever seen a pair of these once so I wish the photos turned out better but they were so far away. I was alone on a cliff edge in Silverdale just watching them repeatedly dive for food, it was the most at peace I have ever felt. They mate for life and give their partner gifts and dance for them. They are just like us but with more hair than me.`,
        imageCount: 1,
        date: `07/03/2026`,
        location: `Silverdale`,
        whatStatus: ``,
    }, {
        name: `Redshank`,
        summary: `I feel nothing about this bird. No that's mean, but it is kinda true. At least compared to other waders, it's easy to recognise thanks to it's bright red legs and beak. But I am more of a dunlin man.`,
        imageCount: 2,
        date: `25/01/2026`,
        location: `West Kirby`,
        whatStatus: ``,
    }, {
        name: `Redwing`,
        summary: `One of the first birds I started hoping to see when I was out in woodland at the start of the year. And thankfully I did see it. They have a red armpit which helps identify it from other thrushes, and they love to eat berries.`,
        imageCount: 1,
        date: `03/01/2026`,
        location: `Thurstaston`,
        whatStatus: ``,
    }, {
        name: `Reed Bunting`,
        summary: `When I was in Wigan, I was really hoping to see one of these by the reed beds, and eventually I did. However, it was raining badly so I stood there watching 2 of them fly around waiting for the sun to come but it never did. Teenagers cycled past asking what I was doing and a different guy answered for me saying I was fishing. I was not fishing.`,
        imageCount: 2,
        date: `08/07/2026`,
        location: `Bempton Cliffs`,
        whatStatus: `updated`,
    }, {
        name: `Reed Warbler`,
        summary: `A bird that is a pain in the arse to find. First photo I had of it was out of focus because they move so quickly inside reed beds. So I was happy to get a nice in focus photo of them when I went to Tipton. I sometimes wish I had accidentally gotten a photo of a Sedge Warbler instead as they seem rarer to me.`,
        imageCount: 1,
        date: `02/05/2026`,
        location: `Tipton`,
        whatStatus: ``,
    }, {
        name: `Ring-necked Parakeet`,
        summary: `Noisy invasive species in a lot of parks. Plenty around Liverpool and I remember a lady asking what I was doing, and I'm just like "Photographing birds", as it was a nice day and I was annoyed I hadn't photographed them yet. When I was in London, I saw a mum and her kid feeding them with their hand out, and it was quite sweet.`,
        imageCount: 1,
        date: `06/06/2026`,
        location: `Hyde Park`,
        whatStatus: ``,
    }, {
        name: `Ringed Plover`,
        summary: `Hey, it's that bird from my RSPB Membership guest card. So it was nice to photograph one of them for a reason. It was difficult to photo it back in Hilbre Island as it flew off very easily and was behind some awful deep wet sand that almost caused me to lose my shoe.`,
        imageCount: 1,
        date: `17/05/2026`,
        location: `Hilbre Island`,
        whatStatus: ``,
    }, {
        name: `Rock Dove`,
        summary: `Or a pigeon as we all know it. I love the variety of colour tones we see on pigeons. Very useful in the past so I am glad they still stick around humans and I feel sorry for the ones that kids chase. Often I see a very grey rock dove and take a photo hoping it's a stock dove, but it never is. But now I know to look out for the blacker eyes on stock doves.`,
        imageCount: 3,
        date: `04/01/2026`,
        location: `Birkenhead Park`,
        whatStatus: ``,
    }, {
        name: `Rock Pipit`,
        summary: `A pipit!? Ahhhhh! Okay but this one is quite easy to tell apart from the others. It has very dark legs. And of course it likes to hang out on rocks, hence the name. I think I got lucky to see it at Hilbre Island. Same day I saw it, a Japanese woman asked me where are the seals, I met up again with her later and she was so happy she saw them!`,
        imageCount: 2,
        date: `17/05/2026`,
        location: `Hilbre Island`,
        whatStatus: ``,
    }, {
        name: `Rook`,
        summary: `A bird that is supposed to be common but I have a hard time hearing it. Thankfully I saw one in Wales during the brief sunny dry spell and it's cawww is very different from other corvids. It almost looks prehistoric with how grey the beak is compared to the rest of the body.`,
        imageCount: 1,
        date: `31/01/2026`,
        location: `Bangor`,
        whatStatus: ``,
    },
    {
        name: `Tree Sparrow`,
        summary: `Yay! An actual Tree Sparrow at last. In your face, House Sparrows. Prior to going to the Bempton Cliffs, I heard new Tree Sparrow chicks were seen so I thought just maybe I might see one, and I did. Quite a lot actually. The little black dot on the side of the cheek is what helps identify it from the House Sparrow.`,
        imageCount: 4,
        date: `08/07/2026`,
        location: `Bempton Cliffs`,
        whatStatus: `new`,
    },
    {
        name: `Turnstone`,
        summary: `I love this tiny bird and it's full name is Ruddy Turnstone, which sounds a bit like a curse word. When I started walking along the promenade after my QA job, I would frequently see these and wonder what they were. Now I know! Cute name. Looks a bit like a dunline but lacks the black on the belly, hence why I think dunlins are cuter. Only found alongside our coasts and usually only during the Winter.`,
        imageCount: 1,
        date: `25/01/2026`,
        location: `West Kirby`,
        whatStatus: ``,
    }, {
        name: `Ruff`,
        summary: `A bird I hope to get a better photo of when in breeding season. The males look like absolute drag queens. Otherwise they look quite typical. Tall wader birds lacking in colour.`,
        imageCount: 3,
        date: `12/05/2026`,
        location: `Marshside`,
        whatStatus: ``,
    }, {
        name: `Sand Martin`,
        summary: `An annoying hirundine (the collective name for martins and swallows) to photo, but I feel that way about all of them par the Barn Swallow. Never stops moving. Never stops flying but I do love their little brown ring around the neck.`,
        imageCount: 1,
        date: `11/04/2026`,
        location: `Wigan`,
        whatStatus: ``,
    },
    {
        name: `Sedge Warbler`,
        summary: `Look at that bushy eyebrow. For months, this thing plagued me with its call before I finally spotted one out in the open at Parkgate. And then another. And then another. It's like a delayed bus. `,
        imageCount: 3,
        date: `28/06/2026`,
        location: `Parkgate`,
        whatStatus: ``,
    }, {
        name: `Shag`,
        summary: `I hope this is a photo of a Shag. It was very far out into sea and I can't make out the colour features of the beak that a cormorant has. As a result, I sam saying this is a shag. Named for it's unkempt look, not cos it likes to fool around.`,
        imageCount: 1,
        date: `18/04/2026`,
        location: `Holyhead`,
        whatStatus: ``,
    }, {
        name: `Shelduck`,
        summary: `Another duck I love! It always looks lonely and sad. The bright red beak is an easy giveaway to know if it's a Shelduck and not one of 200 other ducks.`,
        imageCount: 2,
        date: `27/04/2026`,
        location: `Marshside`,
        whatStatus: ``,
    }, {
        name: `Shoveler`,
        summary: `Now this, is one grumpy looking duck. Has a really long beak that is so long, it looks painful, and I often feel that way when I see old men with large noses. Surely it must hurt?`,
        imageCount: 3,
        date: `22/02/2026`,
        location: `Marshside`,
        whatStatus: ``,
    }, {
        name: `Siskin`,
        summary: `I love this small yellowish bird. Again despite the awful rain, Bangor served me well during the brief sunny spell and I saw a few of them. I also could've gotten a better photo but it was on the path infront of a running woman, and I didn't wanna seem weird. `,
        imageCount: 1,
        date: `31/01/2026`,
        location: `Bangor`,
        whatStatus: ``,
    }, {
        name: `Skylark`,
        summary: `I always thought this was a really cool name, and then I saw behaviour that gave it the name. The male will fly up into the SKY, almost vertically like a spaceship, and then causes a LARK by never shutting up. Hard bird to find.`,
        imageCount: 1,
        date: `18/04/2026`,
        location: `Holyhead`,
        whatStatus: ``,
    }, {
        name: `Song Thrush`,
        summary: `A bird that when I first heard it, I was so amazed by the song I didn't want to possibly scare it off. So as I turned a corner to photo it, it flew off, but landed in a much better spot. That said, is often hard to find as they like to hide deep into trees. I visibly cannot tell the difference between this and a Mistle Thrush`,
        imageCount: 3,
        date: `22/06/2026`,
        location: `Royden Park`,
        whatStatus: ``
    }, {
        name: `Starling`,
        summary: `Adorable bird that loves to hang out in car parks in groups like a bunch of teenagers. The iridescent feathers and the beak having 3 colours during breeding season which makes them a joy to photo. Have yet to see a murmuration but hope to one day.`,
        imageCount: 1,
        date: `10/01/2026`,
        location: `Liverpool to Leeds Canal`,
        whatStatus: ``,
    }, {
        name: `Stonechat`,
        summary: `They got their name from their call which sounds like 2 stones being scraped together. They look like a fancier more gothic robin and I really like photographing them. The males are darker in tone than the females.`,
        imageCount: 5,
        date: `17/01/2026`,
        location: `Lunt Meadows`,
        whatStatus: ``,
    }, {
        name: `Teal`,
        summary: `Duck with a coloured head that reminds me of a dirty tennis ball. Not much to say other than like a lot of other ducks, the female is hard to separate from other species. I should photograph more for how common they are.`,
        imageCount: 1,
        date: `17/01/2026`,
        location: `Lunt Meadows`,
        whatStatus: ``,
    }, {
        name: `Treecreeper`,
        summary: `I love this egg shaped bird. It moves up a tree like a squirrel by hopping from the bottom to the very top before repeating the process again on another tree. Before I got my camera, I saw one in the Heswall Dales and wondered what the hell it was. So kudos to this bird for being an inspiration for me to get into this hobby.`,
        imageCount: 1,
        date: `31/01/2026`,
        location: `Bangor`,
        whatStatus: ``,
    }, {
        name: `Tufted Duck`,
        summary: `A cute small duck. The males have a lovely hairdo but their eyes scare me a little. My first time seeing ducks mate was seeing a pair of these, and it scarred me for life. The female looks like she is being drowned, poor lass.`,
        imageCount: 3,
        date: `27/04/2026`,
        location: `Marshside`,
        whatStatus: ``,
    }, {
        name: `Wheatear`,
        summary: `One of my favourite names. hwit, became wheat, which became white, and tear means arse. So it's name translates literally to 'white arse' and it does in fact have a white arse. The prominent eyeliner also helps it stand out.`,
        imageCount: 3,
        date: `18/04/2026`,
        location: `Holyhead`,
        whatStatus: ``,
    }, {
        name: `Wigeon`,
        summary: `A brown headed duck with a white stripe going along it, that helps separate it from a pochard. Not much to say other than, it's yet another duck. There are too many ducks. `,
        imageCount: 1,
        date: `22/02/2026`,
        location: `Marshside`,
        whatStatus: ``,
    }, {
        name: `Willow Warbler`,
        summary: `Looks like a Chiffchaff, but sounds nothing like it. I had a lot of difficulty finding them despite my phone app alerting me of them aplenty. The day I finally got one, it was incredibly windy but it held it's ground on a stick and posed for me for a good while. Thanks birdy!`,
        imageCount: 1,
        date: `11/04/2026`,
        location: `Wigan`,
        whatStatus: ``,
    }, {
        name: `Woodpigeon`,
        summary: `There's something about the woodpigeon I like! It's like a pigeon that is dressed for a gala but too cheap to afford a nice suit. I love their twit twoo twoo twit calls. And they are often quite chunky looking which I also like. Big bird gotta eat!`,
        imageCount: 5,
        date: `29/04/2026`,
        location: `Thurstaston`,
        whatStatus: ``,
    }, {
        name: `Wren`,
        summary: `An incredibly loud bird and especially for it's size. The human equivalent would be us making the sound of a foghorn. Difficult to spot these small brown birds but at least you can hear them.`,
        imageCount: 2,
        date: `11/05/2026`,
        location: `Thurstaston`,
        whatStatus: ``,
    }, {
        name: `Lesser Black-backed Gull`,
        summary: `A gull with yellow legs but is not a yellow-legged gull. Oh the humanity. That said, these are the most likely ones people see when spotting a gull with yellow legs. Was happy to get a photo of one perched on a rock in a natural looking area by water unlike the ones that fly around Liverpool stealing my food.`,
        imageCount: 2,
        date: `11/04/2026`,
        location: `Horrock's Flash`,
        whatStatus: ``,
    }, {
        name: `Blackcap`,
        summary: `A bird that I heard early on in Spring yet took far too long to get a decent photo of. They seem to love hiding in bushes. Despite the name 'Blackcap' only the males have the black cap whereas the top of females are brown. A random walk around the Lunt Nature Reserve on a Sunday led me to finally getting a photo.`,
        imageCount: 2,
        date: `31/05/2026`,
        location: `Lunt Meadows`,
        whatStatus: ``,
    }, {
        name: `Robin`,
        summary: `One of my favourite birds to photograph as they are frequently on branches at chest height. We associate them a lot with Winter but that's mostly because other birds quiet down or migrate, so they are the last few left singing. They are quite territorial which makes them fitting as Britain's unofficial national bird.`,
        imageCount: 5,
        date: `03/01/2026`,
        location: `Thurstaston`,
        whatStatus: ``,
    }, {
        name: `Blue Tit`,
        summary: `An absolutely cutie pie of a bird. Apparently the males with the bluest heads are the most likely to get the females. The word tit used to mean small thing which is why so many birds are called tits. They sync up their laying of eggs with the caterpillar season so if you see one with a caterpillar, you may be able to see it fly back to the nest.`,
        imageCount: 6,
        date: `11/05/2026`,
        location: `Thurstaston`,
        whatStatus: ``,
    }, {
        name: `Jay`,
        summary: `A shy member of the Corvidae family. Perhaps the most colourful corvid. I remember seeing what I thought was 2 woodpigeons in the distance but then as I got closer I thought "hmm, something is different" and then it flew behind a hedge. So I stalked it for a while and it kept hopping away so I could only photograph it from behind. A lovely old lady walking her dog asked me what I saw and I guessed right that it was a Jay!`,
        imageCount: 4,
        date: `30/05/2026`,
        location: `Thurstaston`,
        whatStatus: ``,
    }, {
        name: `Little Egret`,
        summary: `One pretty bird that loves to keep its distance. May often see it stalking fish in water. Sometimes looks a bit like Doc Brown from Back to the Future. Would love to see a different kind of Egret one day but it's looking less likely, the Cattle Egret especially is really colourful.`,
        imageCount: 7,
        date: `17/01/2026`,
        location: `Lunt Meadows`,
        whatStatus: ``,
    }
]

birddata.sort((a, b) => a.name.localeCompare(b.name));

export default birddata;