const birddata = [
    {
        name: `Avocet`,
        summary: `The bird from the RSPB logo! I have only ever seen it alone at the Marshside Nature Reserve in Southport on 2 different locations, and it's often very far away.`,
        images: ["1", "2"],
        date: `27/04/2026`,
        location: `Marshside Nature Reserve`,
    }, {
        name: `Black Swan`,
        summary: `Visited a friend in London hoping to see some birds and despite the awful rain, I saw this celebrity. Had about 4 eggs, one slightly cracked. It kept bothering a Mute Swan to further build up the nest. Glad the trip was not wasted! Native to Australia but some escapees have successfully bred in UK, especially in Devon.`,
        images: ["1", "2", "3", "4"],
        date: `06/06/2026`,
        location: `Hyde Park`,
    }, {
        name: `Blackbird`,
        summary: `Female is brown so I hate the name! Often seen in Winter on the ground flicking leaves around but in Spring, it loves to sing early in the morning and is the first heard during the 'Dawn chorus' Prominent ring around the eye helps distinguish it from other small brown birds.`,
        images: ["1", "2", "3"],
        date: `11/05/2026`,
        location: `Thursaston`,
    }, {
        name: `Barn Swallow`,
        summary: `Or Swallow as it's just called in the UK. Prongs on the tail helps it stand out from other swallows. Arrives in April then leaves around October. Fast flyers but thankfully unlike Sand Martins they do like to rest now and then which makes for easier photographing.`,
        images: ["1", "2", "3"],
        date: `18/04/2026`,
        location: `Holyhead`,
    }, {
        name: `Black-headed Gull`,
        summary: `A cute small gull but I hate the name. The black-head it's named for is only there during breeding season, otherwise it's more of an ink smudge. At least I can tell this gull apart from other gulls thanks to the red break.`,
        images: ["1", "2"],
        date: `05/01/2026`,
        location: `West Kirby`,
    }, {
        name: `Black-tailed Godwit`,
        summary: `Large wader that in Summer have brighter orange chests. Sadly my photo was taken in Winter which is when they are the most common in the UK and also means it looks a bit drab. That said, was happy to get a photo of it at Southport`,
        images: ["1"],
        date: `22/02/2026`,
        location: `Marshside`,
    }, {
        name: `Brent Goose`,
        summary: `An uncommon goose only here during the Winter and along our coasts. Arrives in October and leaves in April so just about got to these in time. eBird really helped me figure out how to find them and easy access to Hilbre Island made it possible. The white patch on the neck helps it stand out from other geese.`,
        images: ["1", "2"],
        date: `06/04/2026`,
        location: `Hilbre Island`,
    }, {
        name: `Buzzard`,
        summary: `Huge bird I mostly see in the air far away. In 2025, I was very lucky to get a photo of one that landed nearby and spoke to an old man about it who asked me if I worked for Naturewatch and said it was a Peregrine Falcon. Wrexham was quite disappointing bird wise as I got lost easily so glad I got this photo.`,
        images: ["1", "2"],
        date: `10/05/2026`,
        location: `Wrexham`,
    }, {
        name: `Canada Goose`,
        summary: `Honk! Accidentally disturbed a nest on a very tiny almost inaccessible island when I was in Wigan but I quickly left em alone. Since then I have seen goslings everywhere and maybe now, I have come to like these birds, sorta. I love how happy the goslings appear and yet the parents look aggressive and miserable.`,
        images: ["1", "2", "3", "4", "5"],
        date: `11/04/2026`,
        location: `Horrock's Flash`,
    }, {
        name: `Chaffinch`,
        summary: `A bird with a lovely song/call. A small amount of repetitive notes followed by a fancy flourish. The males have a lovely colour palette. Often difficult to see through the sticks of trees they perch high upon but at least the colours of the male makes it easier to spot.`,
        images: ["1", "2", "3"],
        date: `02/05/2026`,
        location: `Tipton`,
    }, {
        name: `Chicken`,
        summary: `Should I even count this? I will cos that Silverdale walk was lovely and there was a lot of them.`,
        images: ["1"],
        date: `07/03/2026`,
        location: `Silverdale`,
    }, {
        name: `Chiffchaff`,
        summary: `Got the name from the call it's makes which sounds a lot like "chiff, chaff" over and over. Likes to be very high atop trees which made them difficult to spot the first time I was hearing them. They are small and brown too which didn't help. Once you know the call, it's easy to know when you are near one.`,
        images: ["1", "2"],
        date: `06/04/2026`,
        location: `Thursaston`,
    }, {
        name: `Coal Tit`,
        summary: `A surprisingly hard bird to find. I love their muted colours. Often I photograph a great tit hoping it's a coal tit, but sadly not. I was in Princes Park once and saw one flying about with some lovely trees with pink leaves in the background but there was too many kids around so I didn't get my camera out. Maybe next time!`,
        images: ["1"],
        date: `10/05/2026`,
        location: `Wrexham`,
    }, {
        name: `Collared Dove`,
        summary: `One of many doves I have found and barely seen since. Glad I got this photo when I did. Originally from Asia. They are named after their strip along the neck resembling a collar.`,
        images: ["1"],
        date: `10/01/2026`,
        location: `Liverpool to Leeds Canal`,
    }, {
        name: `Common Whitethroat`,
        summary: `Originally I didn't know there was two types of Whitethroat but then this one looked different to my other and I learned thanks to the RSPB that there was both Common and Lesser. Summer visitor so here between April and October. Very noisy and is named after the white throat it has.`,
        images: ["1", "2", "3"],
        date: `23/05/2026`,
        location: `Thursaston`,
    }, {
        name: `Coot`,
        summary: `A common sight in all parks that many probably don't know the name of; and a moorhen is usually close by too. The chicks are quite nasty looking. They are bad parents and often kill the one that cries the most.`,
        images: ["1", "2", "3"],
        date: `02/05/2026`,
        location: `Tipton`,
    }, {
        name: `Crow`,
        summary: `Often I see a large crow and think it's a raven but it never is. Smart birds apparently, as they will often take advantage of human behaviour to do things such as breaking the shells of nuts by putting them on roads.`,
        images: ["1", "2"],
        date: `02/05/2026`,
        location: `Tipton`,
    }, {
        name: `Curlew`,
        summary: `April 21st is World Curlew Day! A funny looking bird with a huge beak often seen on farms or coasts. Declining population though which is sad to hear.`,
        images: ["1"],
        date: `22/02/2026`,
        location: `Marshside`,
    }, {
        name: `Dunlin`,
        summary: `A small and social wader found along the coast. I think they're really cute as their black belly in breeding season looks like they sat down in dirt for too long. The Mersey Estuary has up to 50,000 dunlins.`,
        images: ["1", "2"],
        date: `17/05/2026`,
        location: `Hilbre Island`,
    }, {
        name: `Dunnock`,
        summary: `A small bird with a grey ring around the neck. Quiet, shy and spends most of the time on muddy paths similar to Blackbirds. The first time I saw one, it kept flying away from me and hiding in bushes back in the Winter. Often looks grumpy.`,
        images: ["1", "2", "3"],
        date: `01/10/2026`,
        location: `Rimrose Valley Country Park`,
    }, {
        name: `Egyptian Goose`,
        summary: `Saw it alone in Sheffield which was quite sad to see but made it quite special; then I go to London and there's 100s of them! Fancy looking goose compared to others. `,
        images: ["1", "2"],
        date: `28/02/2026`,
        location: `Rother Valley Country Park`,
    }, {
        name: `Eider`,
        summary: `A fancy looking duck, well the males anyway. They sound a lot like Marge Simpson going 'oooo' as if they live in constant surprise. The male puffs up their chest like a balloon in attempt to court the lady ducks.`,
        images: ["1"],
        date: `26/04/2026`,
        location: `Hilbre Island`,
    }, {
        name: `Goldcrest`,
        summary: `UK's smallest bird that weighs the same as a 5p coin. I saw them aplenty when I first got my camera and now I never see them, gutted.`,
        images: ["1"],
        date: `30/12/2025`,
        location: `Thursaston`,
    }, {
        name: `Gadwall`,
        summary: `A dull grey looking duck. I have nothing to note of it, I barely recognise them when next to other female ducks of similar colours.`,
        images: ["1"],
        date: `17/01/2026`,
        location: `Lunt Meadows`,
    }, {
        name: `Goldfinch`,
        summary: `A very sociable bird with a warbly chirpy call. Lovely colours when lit up by the sun. The first photo I took of it was during the greyest UK weather I have ever witnessed.`,
        images: ["1", "2", "3"],
        date: `11/05/2026`,
        location: `Thursaston`,
    }, {
        name: `Goosander`,
        summary: `A sick looking duck because it almost looks like it has a pompadour. Only ever seen it once during the Winter but hoping to keep an eye out for it again towards the end of the year. Only seen it far away deep into a lake.`,
        images: ["1"],
        date: `17/01/2026`,
        location: `Lunt Meadows`,
    }, {
        name: `Grey Partridge`,
        summary: `A bird that scares easily, so easily I don't see it first, which it jumping and yelling scares me more than I scared it. That said, happy to at least get 3 in one shot even if it is awful.`,
        images: ["1"],
        date: `17/01/2026`,
        location: `Thursaston`,
    }, {
        name: `Great Black-backed Gull`,
        summary: `Often I can't tell the difference between the two, but I saw two big seagulls sat down next to eachother with very black backs and eyes that looked small. It had to be a Great Black-backed Gull! Surely? Hmm, now I am doubting it`,
        images: ["1"],
        date: `22/02/2026`,
        location: `Marshside`,
    }, {
        name: `Cormorant`,
        summary: `One of my favourite birds! I feel sorry for it as it often just flaps its wings to dry them off due to them not having as much oil to stop the water clogging the feathers. And in Asian, they are used to catch fish a rope around their neck. Poor birds!`,
        images: ["1", "2", "3", "4", "5"],
        date: `11/04/2026`,
        location: `Wigan`,
    }, {
        name: `Great Crested Grebe`,
        summary: `Ah, the Bloodborne bird (cos of the hair reminding me of the Hunter's Hat). I love how they look. Once saw one pull a worm out of it's cloaca in Tipton and it never occurred to me that birds could get worms.`,
        images: ["1"],
        date: `02/05/2026`,
        location: `Tipton`,
    }, {
        name: `Great Spotted Woodpecker`,
        summary: `Often heard but rarely seen! First photo I took of it, it was obscured by leaves but I remember seeing the lovely flash of red before me as it flew past. Also got a photo of it feeding chicks in a nest which I waited 20 minutes to get. People must've thought I was a madman.`,
        images: ["1", "2"],
        date: `24/05/2026`,
        location: `Royden Park`,
    }, {
        name: `Great Tit`,
        summary: `A Great Smal Thing is what the name translates as. The males have a 'tie' going down their chest whereas the females have a very thin line. The thicker the tie, the more attracted to females, apparently...`,
        images: ["1", "2"],
        date: `10/01/2026`,
        location: `Rimrose Valley Country Park`,
    }, {
        name: `Greater Scaup`,
        summary: `One of the rarest birds I have seen, and yet it looks so plain, poor thing. Male remained at Marine Lake in West Kirby for a long time.`,
        images: ["1"],
        date: `23/05/2026`,
        location: `West Kirby`,
    }, {
        name: `Greenfinch`,
        summary: `Very bright green during the summar and quite sociable with a more nasty call compared to the Goldfinch. Sadly due to the rise in trichomonosis and how easily it spreads, their numbers are declining.`,
        images: ["1", "2"],
        date: `14/02/2026`,
        location: `Thursaston`,
    }, {
        name: `Grey Heron`,
        summary: `I first saw one back in 2025 above me along the Liverpool to Leeds Canal and I thought it was gonna drop down and kill me. Since then, they've become one of my favourite birds to spot.`,
        images: ["1", "2", "3", "4", "5"],
        date: `10/01/2026`,
        location: `Liverpool to Leeds Canal`,
    }, {
        name: `Greylag Goose`,
        summary: `Common goose with a weird mouth and loves to hiss. Often I think they're Pink Footed Geese and get them mixed up easily during the Winter`,
        images: ["1", "2"],
        date: `22/02/2026`,
        location: `Marshside`,
    }, {
        name: `Guillemot`,
        summary: `A bird I first heard as I needed to pee near the breakwater at Holyhead. I heard a yelp from the water, looked around, didn't see nothing for a while but then it showed! Lovely bird.`,
        images: ["1"],
        date: `18/04/2026`,
        location: `Holyhead`,
    }, {
        name: `Herring Gull`,
        summary: `A common gull that I often get mixed up with Great Black-backed Gull. If it's legs are pale and the back is light grey, I assume it's this. I hope! `,
        images: ["1", "2"],
        date: `18/04/2026`,
        location: `Holyhead`,
    }, {
        name: `House Sparrow`,
        summary: `I always photograph these hoping it's a Tree Sparrow but that has never been the case despite being away from houses. Sociable but it's a shame the females are a typical LBJ.`,
        images: ["1", "2", "3", "4", "5", "6", "7"],
        date: `10/05/2026`,
        location: `Wrexham`,
    }, {
        name: `Jackdaw`,
        summary: `I used to think these were just baby or smaller crows, but in the Summer, their colours separate them from other corvids easily. The bright blue eyes are a giveaway too.`,
        images: ["1"],
        date: `22/02/2026`,
        location: `Marshside`,
    }, {
        name: `Kestrel`,
        summary: `Spotted the red wings from behind and thought what the hell is that. I then spent 10 minutes photographing it from below as it stretched, gave me the evil eye and all sorts. It was quite intimate! Then in Holyhead I saw one bite the head off a lizard and then swallow it. urgh`,
        images: ["1", "2", "3", "4", "5"],
        date: `10/01/2026`,
        location: `Rimrose Valley Country Park`,
    },
    {
        name: `Blackcap`,
        summary: `A bird that I heard early on in Spring yet took far too long to get a decent photo of. They seem to love hiding in bushes. Despite the name 'Blackcap' only the males have the black cap whereas the top of females are brown. A random walk around the Lunt Nature Reserve on a Sunday led me to finally getting a photo.`,
        images: ["1", "2"],
        date: `31/05/2026`,
        location: `Lunt Meadows`,
    }, {
        name: `Robin`,
        summary: `One of my favourite birds to photograph as they are frequently on branches at chest height. We associate them a lot with Winter but that's mostly because other birds quiet down or migrate, so they are the last few left singing. They are quite territorial which makes them fitting as Britain's unofficial national bird.`,
        images: ["1", "2", "3"],
        date: `03/01/2026`,
        location: `Thursaston`,
    }, {
        name: `Blue Tit`,
        summary: `An absolutely cutie pie of a bird. Apparently the males with the bluest heads are the most likely to get the females. The word tit used to mean small thing which is why so many birds are called tits. They sync up their laying of eggs with the caterpillar season so if you see one with a caterpillar, you may be able to see it fly back to the nest.`,
        images: ["1", "2", "3", "4", "5", "6"],
        date: `11/05/2026`,
        location: `Thursaston`,
    }, {
        name: `Jay`,
        summary: `A shy member of the Corvidae family. Perhaps the most colourful corvid. I remember seeing what I thought was 2 woodpigeons in the distance but then as I got closer I thought "hmm, something is different" and then it flew behind a hedge. So I stalked it for a while and it kept hopping away so I could only photograph it from behind. A lovely old lady walking her dog asked me what I saw and I guessed right that it was a Jay!`,
        images: ["1", "2", "3"],
        date: `30/05/2026`,
        location: `Thursaston`,
    }, {
        name: `Little Egret`,
        summary: `One pretty bird that loves to keep its distance. May often see it stalking fish in water. Sometimes looks a bit like Doc Brown from Back to the Future. Would love to see a different kind of Egret one day but it's looking less likely, the Cattle Egret especially is really colourful.`,
        images: ["1", "2", "3", "4", "5", "6"],
        date: `17/01/2026`,
        location: `Lunt Meadows`,
    }
]

birddata.sort((a, b) => a.name.localeCompare(b.name));

export default birddata;